### PR TITLE
Add JPEG XL support

### LINKED ISSUE #4: GThumb from flathub doesn't bundle support for JPEG XL?
GThumb 3.12 supports JXL, but the version packaged in flathub doesn't seem to have it? Or am I imagining things?

### PR DESCRIPTION
**Pull request by fedelibre**
Fix #4 

The build is failing on my computer while building the highway module and I can't understand why. It seems a DNS failure:

```
-- Build files have been written to: /run/build/highway/googletest-download
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
-- Had to git clone more than once:
          3 times.
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/google/googletest.git'


make[2]: *** [CMakeFiles/googletest.dir/build.make:99: googletest-prefix/src/googletest-stamp/googletest-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/googletest.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
CMake Error at CMakeLists.txt:316 (message):
  Build step for googletest failed: 2
```

or maybe the fact that there's no master branch? Default branch is main.
I'd rather disable googletest, if possible.

### CODE REVIEW

**Comment by fedelibre** [comment]
> I'd rather disable googletest, if possible.

Ok, `-DBUILD_TESTING=OFF` works.

**Comment by fedelibre** [comment]
The installed size increased a lot:

```
$ flatpak info org.gnome.gThumb//stable | grep Installed
   Installed: 84.0 MB

$ flatpak info org.gnome.gThumb//master | grep Installed
   Installed: 241.1 MB
```

I'm not sure what else I may clean up.
Any help appreciated @miabbott @tim77 @hfiguiere

**Comment by hfiguiere** [comment]
Leftover static libraries? I would need to build and compare otherwise.

**Comment by fedelibre** [comment]
> Leftover static libraries? I would need to build and compare otherwise.

I think you guessed right. There's a 100M libjxl.a file.
.a and .la file can be always be removed?

```
[📦 org.gnome.gThumb ~]$ ls -lh /app/lib | sort -h
drwxr-xr-x. 1 fede fede    0 Jan  1  1970 debug
drwxr-xr-x. 1 fede fede   10 Jan  1  1970 cmake
drwxr-xr-x. 1 fede fede  148 Jan  1  1970 colord-sensors
drwxr-xr-x. 1 fede fede   20 Jan  1  1970 gthumb
drwxr-xr-x. 1 fede fede  344 Jan  1  1970 pkgconfig
drwxr-xr-x. 1 fede fede   86 Jan  1  1970 girepository-1.0
drwxr-xr-x. 1 fede fede    8 Jan  1  1970 systemd
lrwxrwxrwx. 1 fede fede   13 Nov 23 23:24 libjxl.so -> libjxl.so.0.6
lrwxrwxrwx. 1 fede fede   14 Nov 23 23:24 libexiv2.so -> libexiv2.so.27
lrwxrwxrwx. 1 fede fede   15 Nov 23 23:24 libjxl.so.0.6 -> libjxl.so.0.6.1
lrwxrwxrwx. 1 fede fede   16 Nov 23 23:24 libraw.so.20 -> libraw.so.20.0.0
lrwxrwxrwx. 1 fede fede   16 Nov 23 23:24 libraw.so -> libraw.so.20.0.0
lrwxrwxrwx. 1 fede fede   17 Nov 23 23:24 libde265.so.0 -> libde265.so.0.1.1
lrwxrwxrwx. 1 fede fede   17 Nov 23 23:24 libde265.so -> libde265.so.0.1.1
lrwxrwxrwx. 1 fede fede   17 Nov 23 23:24 libheif.so.1 -> libheif.so.1.12.0
lrwxrwxrwx. 1 fede fede   17 Nov 23 23:24 libheif.so -> libheif.so.1.12.0
lrwxrwxrwx. 1 fede fede   18 Nov 23 23:24 libcolord.so.2 -> libcolord.so.2.0.5
lrwxrwxrwx. 1 fede fede   18 Nov 23 23:24 libcolord.so -> libcolord.so.2.0.5
lrwxrwxrwx. 1 fede fede   18 Nov 23 23:24 libexiv2.so.27 -> libexiv2.so.0.27.4
lrwxrwxrwx. 1 fede fede   18 Nov 23 23:24 libraw_r.so.20 -> libraw_r.so.20.0.0
lrwxrwxrwx. 1 fede fede   18 Nov 23 23:24 libraw_r.so -> libraw_r.so.20.0.0
lrwxrwxrwx. 1 fede fede   21 Nov 23 23:24 libjxl_threads.so -> libjxl_threads.so.0.6
lrwxrwxrwx. 1 fede fede   23 Nov 23 23:24 libjxl_threads.so.0.6 -> libjxl_threads.so.0.6.1
lrwxrwxrwx. 1 fede fede   23 Nov 23 23:24 libtotem-plparser.so -> libtotem-plparser.so.18
lrwxrwxrwx. 1 fede fede   25 Nov 23 23:24 libcolordprivate.so.2 -> libcolordprivate.so.2.0.5
lrwxrwxrwx. 1 fede fede   25 Nov 23 23:24 libcolordprivate.so -> libcolordprivate.so.2.0.5
lrwxrwxrwx. 1 fede fede   27 Nov 23 23:24 libtotem-plparser.so.18 -> libtotem-plparser.so.18.3.5
lrwxrwxrwx. 1 fede fede   28 Nov 23 23:24 libtotem-plparser-mini.so -> libtotem-plparser-mini.so.18
lrwxrwxrwx. 1 fede fede   32 Nov 23 23:24 libtotem-plparser-mini.so.18 -> libtotem-plparser-mini.so.18.3.5
-rw-r--r--. 5 fede fede 100M Jan  1  1970 libjxl.a
-rw-r--r--. 5 fede fede  10M Jan  1  1970 libexiv2-xmp.a
-rw-r--r--. 5 fede fede 1.4M Jan  1  1970 libcolordprivate.a
-rw-r--r--. 5 fede fede  15M Jan  1  1970 libheif.a
-rw-r--r--. 5 fede fede  20M Jan  1  1970 libde265.a
-rw-r--r--. 5 fede fede  293 Jan  1  1970 colord.service
-rw-r--r--. 5 fede fede 348K Jan  1  1970 libjxl_threads.a
-rw-r--r--. 5 fede fede  42K Jan  1  1970 libhwy_test.a
-rw-r--r--. 5 fede fede  46M Jan  1  1970 libjxl_dec.a
-rw-r--r--. 5 fede fede 5.0K Jan  1  1970 69-cd-sensors.rules
-rw-r--r--. 5 fede fede 568K Jan  1  1970 libhwy.a
-rw-r--r--. 5 fede fede  63K Jan  1  1970 libhwy_contrib.a
-rw-r--r--. 5 fede fede   78 Jan  1  1970 colord.conf
-rw-r--r--. 5 fede fede  847 Jan  1  1970 95-cd-devices.rules
-rw-r--r--. 5 fede fede 978K Jan  1  1970 libcolord.a
-rw-r--r--. 8 fede fede 6.3M Jan  1  1970 libraw.a
-rw-r--r--. 8 fede fede 6.3M Jan  1  1970 libraw_r.a
-rwxr-xr-x. 5 fede fede 1.1K Jan  1  1970 libcolord.la
-rwxr-xr-x. 5 fede fede 1.1K Jan  1  1970 libcolordprivate.la
-rwxr-xr-x. 5 fede fede 1.1M Jan  1  1970 libraw_r.so.20.0.0
-rwxr-xr-x. 5 fede fede 1.1M Jan  1  1970 libraw.so.20.0.0
-rwxr-xr-x. 5 fede fede 159K Jan  1  1970 libcolord.so.2.0.5
-rwxr-xr-x. 5 fede fede 167K Jan  1  1970 libtotem-plparser.so.18.3.5
-rwxr-xr-x. 5 fede fede 232K Jan  1  1970 libcolordprivate.so.2.0.5
-rwxr-xr-x. 5 fede fede  23K Jan  1  1970 libjxl_threads.so.0.6.1
-rwxr-xr-x. 5 fede fede  31K Jan  1  1970 libtotem-plparser-mini.so.18.3.5
-rwxr-xr-x. 5 fede fede 3.1M Jan  1  1970 libjxl.so.0.6.1
-rwxr-xr-x. 5 fede fede 3.2M Jan  1  1970 libexiv2.so.0.27.4
-rwxr-xr-x. 5 fede fede 595K Jan  1  1970 libheif.so.1.12.0
-rwxr-xr-x. 5 fede fede 855K Jan  1  1970 libde265.so.0.1.1
-rwxr-xr-x. 5 fede fede  946 Jan  1  1970 libraw.la
-rwxr-xr-x. 5 fede fede  953 Jan  1  1970 libde265.la
-rwxr-xr-x. 5 fede fede  960 Jan  1  1970 libraw_r.la
-rwxr-xr-x. 5 fede fede  985 Jan  1  1970 libheif.la
total 217M
```

**Comment by hfiguiere** [comment]
a `*.a` in the top level cleanup. Might even make the flatpak smaller than before this PR.

**Comment by hfiguiere** [comment]
and `*.la`

**Comment by fedelibre** [comment]
Indeed, it went down from 84MB to 24.9MB.

**Comment by tim77** [comment]
> Indeed, it went down from 84MB to 24.9MB.

Awesome 👍. Can't test and tinker with this right now, sorry.

**Pull request merged**
